### ISSUE TITLE
Crypto module

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#11]

**Comment by m-stein** [comment]
I have created a first version of the Crypto module in SPARK that compiles and contains all functionality. It can be reproduced via my "cbe" branches in my repos "libsparkcrypto", "genode" and "genode-world". It's not based on the most recent stable CBE version of @cnuke but on that one step before (still based on 19.02).

Unfortunately I didn't get it to link as presumably there is some ``SRC_ADS`` stuff missing in the import MK file of the libsparkcrypto port. But when I add ``lsc-aes.ads`` and its vpath - as the toolchain suggests through ``error: "lsc-aes.ali" not found, "lsc-aes.adb" must be compiled`` - the toolchain gives me a pretty generic error ``cannot generate code for file lsc-aes.ads (package spec)``. Which is strange as the same approach already worked for ``lsc.ads`` before.

**Comment by senier** [comment]
Contrary to `lsc.ads`, `lsc-aes.ads` *does have* a body. Hence, you must not add it to `SRC_ADS`, but you should only add the body `lsc-aes.adb` to `SRC_ADB`. Otherwise, the compiler tries to compile the spec and complains that it has subprograms and must not be compiled alone (as you saw).

**Comment by m-stein** [comment]
@senier Thanks for this fast feedback!
I tried to add ADB files too, just to give it a try, but then I end up adding the whole library to the import MK. There must be something I'm doing wrong in the first place. I would expect it just to work when stating ``LIBS += aes_cbc_4k``. After all, it works with the aes_cbc_4k test too.

**Comment by m-stein** [comment]
I recognized that building the CBE with the spark crypto module calls gnatbind as follows:
```
 genode-x86-gnatbind -n -we
-I.../build/x86_64/var/libcache/libsparkcrypto
...
-I.../ada-runtime/src/minimal
...
-I.../libsparkcrypto/src/ada/generic
...
--RTS=.../build/x86_64/var/libcache/spark -o
b~spark_cbe.adb cbe.ali cbe-cxx-cxx_pool.ali cbe-cxx-cxx_splitter.ali
cbe-cxx-cxx_primitive.ali cbe-cxx-cxx_request.ali cbe-cxx.ali cbe-splitter.ali
cbe-primitive.ali cbe-request.ali cbe-pool.ali cbe-crypto.ali aes_cbc_4k.ali
```
which causes:
```
error: "lsc.ali" not found, "lsc.ads" must be compiled
```
In contrast, building test/aes_cbc_4k doesn't call gnatbind. Also, if I add a dummy package to the test and let C++ call a function exported by dummy, gnatbind is not called. But as soon as I add ``with Aes_Cbc_4k;`` to dummy and let it use a simple type (``Aes_Cbc_4k.Byte``), gnatbind is called and the same error as with the CBE occurs.

**Comment by m-stein** [comment]
If I hollow out the aes_cbc_4k library, so, it has no dependency to libsparkcrypto while still using Aes_Cbc_4k.Byte in my dummy package, gnatbind is called but doesn't throw the error. I think the libsparkcrypto import breaks things.

**Comment by senier** [comment]
I just realized that you seem to be using the 4 months old port of libsparkcrypto from world? Much has changed since, and I'm pretty sure your issues are already solved in the current master state (plus, the old libsparkcrypto API is definitely not what you want to use). Can you please try libsparkcrypto from libports in current master?

**Comment by m-stein** [comment]
@senier Thanks for this hint!
Unfortunately, it didn't solve the error about ``lsc.ads``. I quickfixed it, however, by moving all CBE SPARK code to a library and make the CBE depend on it. The problem seems to occur only when building a program whose own SPARK code "with"s (indirectly) libsparkcrypto packages.

**Comment by m-stein** [comment]
My cbe branches are now rebased to the last stable state used by @cnuke and integrate the spark crypto module into the C++ code. It runs, but triggers a bad block address after a while.

**Comment by cnuke** [comment]
@m-stein I've pushed the [cbe](https://github.com/cnuke/cbe/commits/cbe) branch. It depends on the current version of my [cbe__bump_in_wire](https://github.com/cnuke/genode/commits/cbe__bump_in_wire) branch.

**Comment by m-stein** [comment]
This issue is fixed on current master.
